In [81]:
import pandas as pd
from datetime import datetime

## Limpeza Inicial Countries

In [82]:
countries = pd.read_csv(r'macrodata\gdp-per-capita-worldbank.csv')
countries.drop(columns='Code',inplace=True)
countries.reset_index(drop=True, inplace=True)

# Muda o nome de entity para country_name para ficar igual ao nome da coluna do player_values
countries.rename(columns={'Entity': 'Country Name'}, inplace=True)
countries

     Country Name  Year  GDP per capita World region according to OWID
0     Afghanistan  2000       1617.8264                           Asia
1     Afghanistan  2001       1454.1108                           Asia
2     Afghanistan  2002       1774.3087                           Asia
3     Afghanistan  2003       1815.9282                           Asia
4     Afghanistan  2004       1776.9182                           Asia
...           ...   ...             ...                            ...
7235     Zimbabwe  2020       4527.7197                         Africa
7236     Zimbabwe  2021       4827.0890                         Africa
7237     Zimbabwe  2022       5036.7610                         Africa
7238     Zimbabwe  2023       5218.0225                         Africa
7239     Zimbabwe  2024       5215.2530                         Africa

[7240 rows x 4 columns]

## Limpeza Inicial football

In [87]:
club_fin = pd.read_csv(r'football\club_financials.csv')
leagues = pd.read_csv(r'football\league_metrics.csv')
player_values = pd.read_csv(r'football\player_market_values.csv')
player_full = pd.read_csv(r'football\players.csv', engine='python', on_bad_lines='skip')
records = pd.read_csv(r'football\record_transfers.csv')
all_transfers = pd.read_csv(r'football\transfers_history.csv')

# Check if players in player_values are also in player_full, if so add a country collum to player_values of the players country of origin
player_values = player_values.merge(
    player_full[['name', 'country_of_birth']],
    how='left',
    left_on='player_name',
    right_on='name'
)
player_values.drop(columns='name', inplace=True)

# Arrumar o país de origem dos jogadores que não tem, a partir do dicionário de jogadores e países
jogadores_paises = {
    "Luis Suarez": "Uruguay",
    "Luka Modric": "Croatia",
    "Mesut Ozil": "Germany",
    "Vinicius Jr": "Brazil",
    "Sadio Mane": "Senegal",
    "Aurelien Tchouameni": "France",
    "Moises Caicedo": "Ecuador",
    "Pau Cubarsi": "Spain",
    "Antonio Rudiger": "Germany",
    "Joao Cancelo": "Portugal",
    "Theo Hernandez": "France",
    "Andy Robertson": "Scotland",
    "Alisson Becker": "Brazil",
    "Andre Onana": "Cameroon",
    "Warren Zaire-Emery": "France",
    "Arda Guler": "Turkey",
    "Fermin Lopez": "Spain",
    "Joao Neves": "Portugal",
    "Estevão Willian": "Brazil",
    "Martin Odegaard": "Norway",
    "Lautaro Martinez": "Argentina",
    "Dusan Vlahovic": "Serbia",
    "Rasmus Hojlund": "Denmark",
    "Niklas Sule": "Germany"
}

for player, country in jogadores_paises.items():
    player_values.loc[player_values['player_name'] == player, 'country_of_birth'] = country

# # Mudar England para United Kingdom, pois é o nome que está na lista de países do macrodata
player_values.loc[player_values['country_of_birth'] == 'England', 'country_of_birth']  = 'United Kingdom'
player_values.loc[player_values['country_of_birth'] == 'Scotland', 'country_of_birth']  = 'United Kingdom'
player_values.loc[player_values['country_of_birth'] == 'Korea, South', 'country_of_birth']  = 'South Korea'
player_values.loc[player_values['country_of_birth'] == 'East Germany (GDR)', 'country_of_birth']  = 'Germany'

# Ver se todos os países dos jogadores estão na lista de países do macrodata e imprimir alguns jogadores que não estão na lista de países do macrodata
# paises_macrodata = countries['Country Name'].unique()
# total_jogadores = player_values.shape[0]
# jogadores_com_pais = player_values['country_of_birth'].isin(paises_macrodata).sum()
# jogadores_sem_pais = player_values[~player_values['country_of_birth'].isin(paises_macrodata)]
# print(jogadores_sem_pais)

player_values['year_of_birth'] = player_values['year']-player_values['age']
player_values

,year,player_name,age,position,market_value_eur_m,is_peak_year,country_of_birth,year_of_birth
0,2010,Lionel Messi,23,FW,12.0,0,Argentina,1987
1,2011,Lionel Messi,24,FW,9.9,0,Argentina,1987
2,2012,Lionel Messi,25,FW,11.3,0,Argentina,1987
3,2013,Lionel Messi,26,FW,24.5,0,Argentina,1987
4,2014,Lionel Messi,27,FW,53.8,0,Argentina,1987
...,...,...,...,...,...,...,...,...
1108,2022,Memphis Depay,28,FW,3.3,0,Netherlands,1994
1109,2023,Memphis Depay,29,FW,2.5,0,Netherlands,1994
1110,2024,Memphis Depay,30,FW,2.5,0,Netherlands,1994
1111,2025,Memphis Depay,31,FW,2.5,0,Netherlands,1994
1112,2026,Memphis Depay,32,FW,2.5,0,Netherlands,1994